apiVersion: v1
kind: Service
metadata:
  name: iot4i-transformer-js-service
  labels:
    app: iot4itransformerjs
    tier: iot4i
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  # type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 5000
  selector:
    app: iot4itransformerjs
    tier: iot4i
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iot4itransformerjs
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 2
  template:
    metadata:
      labels:
        app: iot4itransformerjs
        tier: iot4i
    spec:
      containers:
      - name: iot4itransformerjs
        image: registry.stage1.ng.bluemix.net/iot4i/iot4itransformerjs
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
